PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

PREFIX eg: <http://www.semanticweb.org/tbohne-p15s/ontologies/2022/6/diag_ontology#>

# QUERY FAULT CAUSES BY DTC

SELECT ?cause ?condition WHERE {
    eg:P0138 eg:represents ?condition .
    ?cause a eg:FaultCause .
    ?condition eg:hasCause ?cause .
}

# QUERY FAULT CONDITION BY DTC

SELECT ?condition WHERE {
    eg:P0138 eg:represents ?condition .
}

# QUERY SYMPTOMS BY DTC

SELECT ?symptom WHERE {
    eg:P0138 eg:represents ?condition .
    ?symptom a eg:Symptom .
    ?condition eg:manifestedBy ?symptom .
}

# QUERY CORRECTIVE ACTIONS BY DTC

SELECT ?action WHERE {
    eg:P0138 eg:represents ?condition .
    ?action eg:deletes eg:P0138 .
    ?action eg:resolves ?condition .
    ?condition a eg:FaultCondition .
    ?action a eg:CorrectiveAction .
}

# QUERY FAULT DESCRIPTION BY DTC

SELECT ?description WHERE {
    eg:P0138 eg:hasDescription ?description .
    ?description a eg:FaultDescription .
    eg:P0138 a eg:DTC .
}

# QUERY FAULT CATEGORY BY DTC

SELECT ?cat WHERE {
    eg:P0138 eg:hasCategory ?cat .
    ?cat a eg:FaultCategory .
    eg:P0138 a eg:DTC .
}

# QUERY SUGG. MEASURING POS

SELECT ?measuring_pos WHERE {
    eg:P0138 eg:implies ?measuring_pos .
    ?measuring_pos a eg:MeasuringPos .
    eg:P0138 a eg:DTC .
}
