PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX eg: <http://www.semanticweb.org/diag_ontology#>

# Example queries with OBD code P0138

# QUERY FAULT CAUSES BY DTC

SELECT ?cause ?condition WHERE {
    eg:P0138 eg:represents ?condition .
    ?cause a eg:FaultCause .
    ?condition eg:hasCause ?cause .
}

# QUERY FAULT CONDITION BY DTC

SELECT ?condition WHERE {
    eg:P0138 eg:represents ?condition .
}

# QUERY SYMPTOMS BY DTC

SELECT ?symptom WHERE {
    eg:P0138 eg:represents ?condition .
    ?symptom a eg:Symptom .
    ?condition eg:manifestedBy ?symptom .
}

# QUERY CORRECTIVE ACTIONS BY DTC

SELECT ?action WHERE {
    eg:P0138 eg:represents ?condition .
    ?action eg:deletes eg:P0138 .
    ?action eg:resolves ?condition .
    ?condition a eg:FaultCondition .
    ?action a eg:CorrectiveAction .
}

# QUERY FAULT DESCRIPTION BY DTC

SELECT ?description WHERE {
    eg:P0138 eg:hasDescription ?description .
    ?description a eg:FaultDescription .
    eg:P0138 a eg:DTC .
}

# QUERY FAULT CATEGORY BY DTC

SELECT ?cat WHERE {
    eg:P0138 eg:hasCategory ?cat .
    ?cat a eg:FaultCategory .
    eg:P0138 a eg:DTC .
}

# QUERY SUGG. MEASURING POS BY DTC

SELECT ?measuring_pos WHERE {
    eg:P0138 eg:implies ?measuring_pos .
    ?measuring_pos a eg:MeasuringPos .
    eg:P0138 a eg:DTC .
}

# QUERY ALL DTC THAT IMPLY MEASURING POS X

SELECT ?dtc WHERE {
    ?dtc a eg:DTC .
    eg:X a eg:MeasuringPos .
    ?dtc eg:implies eg:X .
}

# QUERY SUSPECT COMPONENTS BY DTC

select ?comp_name where {
    ?comp a eg:SuspectComponent .
    ?diag_association a eg:DiagnosticAssociation .
    ?dtc a eg:DTC .
    ?dtc eg:code "P2563" .
    ?dtc eg:hasAssociation ?diag_association .
    ?diag_association eg:pointsTo ?comp .
    ?comp eg:component_name ?comp_name .
}

# QUERY DTCs OCCURRING WITH THE SPECIFIED DTC

SELECT ?dtc WHERE {
    eg:P0138 eg:occursWith ?dtc .
    ?dtc a eg:DTC .
    eg:P0138 a eg:DTC .
}

# QUERY VEHICLE (+ HSN / TSN) BY DTC

SELECT ?vehicle ?hsn ?tsn WHERE {
    ?fc eg:occurredIn ?vehicle .
    ?fc a eg:FaultCondition .
    ?vehicle a eg:Vehicle .
    eg:P0138 eg:represents ?fc .
    ?vehicle eg:HSN ?hsn .
    ?vehicle eg:TSN ?tsn .
}

# QUERY ALL CARS WITH A FAULT CONDITION

SELECT ?model ?hsn ?tsn ?vin ?cond_desc ?car WHERE {
  ?car a eg:Vehicle .
  ?cond a eg:FaultCondition .
  ?cond eg:condition_description ?cond_desc .
  ?car eg:HSN ?hsn .
  ?car eg:TSN ?tsn .
  ?car eg:VIN ?vin .
  ?car eg:model ?model .
  ?cond eg:occurredIn ?car .
}

# QUERY ALL VEHICLE-AGNOSTIC INFO

SELECT ?code ?occ ?cat_desc ?cond_desc ?symp_desc ?comp_name ?prio ?osci WHERE {
    ?dtc a eg:DTC .
    ?dtc eg:code ?code .
    ?dtc eg:occurs_with_DTC ?occ .
    ?dtc eg:hasCategory ?cat .
    ?cat eg:category_name ?cat_desc .
    ?dtc eg:represents ?cond .
    ?cond eg:condition_description ?cond_desc .
    ?cond eg:manifestedBy ?symp .
    ?symp eg:symptom_description ?symp_desc .
    ?dtc eg:pointsTo ?sus_comp .
    ?sus_comp eg:component_name ?comp_name .
    ?sus_comp eg:priority_id ?prio .
    ?sus_comp eg:use_oscilloscope ?osci .
}

# DTC TEST QUERY - USEFUL FOR DEBUGGING THE KNOWLEDGE ACQUISITION WEB INTERFACE

select ?dtc ?code ?occ ?cond ?symptom ?component where {
    ?dtc a eg:DTC .
    ?dtc eg:code "P0XXX" .
    ?dtc eg:occurs_with_DTC ?occ .
    ?fc a eg:FaultCondition .
    ?dtc eg:represents ?fc .
    ?fc eg:condition_description ?cond .
    ?symp a eg:Symptom .
    ?symp eg:symptom_description ?symptom .
    ?fc eg:manifestedBy ?symp .
    ?sus a eg:SuspectComponent .
    ?da a eg:DiagnosticAssociation .
    ?dtc eg:has ?da .
    ?da eg:pointsTo ?sus .
    ?sus eg:component_name ?component
}

# COMPONENT TEST QUERY - USEFUL FOR DEBUGGING THE KNOWLEDGE ACQUISITION WEB INTERFACE

select ?component ?osci ?aff_by where {
    ?sus a eg:SuspectComponent .
    ?sus eg:component_name ?component .
    ?sus eg:use_oscilloscope ?osci .
    ?sus eg:affected_by ?aff_by .
}

# SUBSYSTEM TEST QUERY - USEFUL FOR DEBUGGING THE KNOWLEDGE ACQUISITION WEB INTERFACE

select ?subsys_name ?containing_comp_name ?verifying_comp_name where {
    ?sub_sys a eg:VehicleSubsystem .
    ?sub_sys eg:subsystem_name ?subsys_name .
    ?containing_comp a eg:SuspectComponent .
    ?containing_comp eg:component_name ?containing_comp_name .
    ?sub_sys eg:contains ?containing_comp .
    ?verifying_comp a eg:SuspectComponent .
    ?verifying_comp eg:verifies ?sub_sys .
    ?verifying_comp eg:component_name ?verifying_comp_name .
}
